call:
  name: Doorbell Ring Notification
  description: Webhook notification when someone is at the door (called by Asterisk). Updates confbridge_id and extension sensors first, then call_status last.
  fields:
    confbridge:
      name: Confbridge ID
      description: The ID of the confbridge being joined by the doorbell
      required: true
      example: "doorbell_front_door"
      selector:
        text:
    extension:
      name: Extension
      description: The extension number that joined the confbridge
      required: true
      example: "9001"
      selector:
        text:

answered:
  name: Call Answered Notification
  description: Webhook notification when a doorbell call is answered (called by Asterisk). Updates confbridge_id and extension sensors first, then call_status last.
  fields:
    confbridge:
      name: Confbridge ID
      description: The ID of the confbridge where the call was answered
      required: true
      example: "doorbell_front_door"
      selector:
        text:
    extension:
      name: Extension
      description: The extension that answered the call
      required: true
      example: "9001"
      selector:
        text:

terminate:
  name: Call Ended Notification
  description: Webhook notification when a doorbell call is terminated (called by Asterisk). Updates confbridge_id sensor first, clears extension, then sets call_status to inactive last.
  fields:
    confbridge:
      name: Confbridge ID
      description: The ID of the confbridge being terminated
      required: true
      example: "doorbell_front_door"
      selector:
        text:
    extension:
      name: Extension
      description: The extension that answered the call
      required: false
      example: "9001"
      selector:
        text:
