[general]
; Nothing here

; Internal Users
[admin_user]
type=user
marked=yes
wait_marked=no
admin=yes
music_on_hold_when_empty=no
quiet=yes
hear_own_join_sound=no
send_events=no

; Video Doorbell User
[default_user]
type=user
admin=no
marked=no
end_marked=yes
send_events=no
music_on_hold_when_empty=yes
quiet=yes
hear_own_join_sound=no
wait_marked=yes

; Conference bridge
[doorbell_front]
type=bridge
max_members=10
enable_events=yes
video_mode=sfu
mixing_interval=20
internal_sample_rate=8000
sound_join=
sound_leave=
sound_kicked=
sound_begin=

; Conference bridge
[doorbell_back]
type=bridge
max_members=10
enable_events=yes
video_mode=sfu
internal_sample_rate=8000
sound_join=
sound_leave=
sound_kicked=
sound_begin=