dingdong:
  name: Incoming doorbell call
  description: Incoming webhook from Asterisk when a doorbell call is initiated
  fields:
    extension:
      name: Confbridge extension
      description: Extension of the confbridge that we need to connect to.
      required: true
      example: "9001"
      selector:
        text:
